#!/bin/sh
# f69 dev-convenience launcher (project root).
# Delegates to `zig-out/bin/run.sh` which carries the actual
# env / ICD / data-dir setup. Regenerated by `zig build portable`.
case "$0" in
    */*) DIR=${0%/*} ;;
    *)   DIR=. ;;
esac
DIR=$(CDPATH= cd -- "$DIR" && pwd)
exec "$DIR/zig-out/bin/run.sh" "$@"
