//! Pure builder for the `aria2c` command line. Centralizing every flag in
//! one tested function (instead of an inline argv in the daemon) keeps the
//! spawn auditable and lets us unit-test the flag set — most importantly
//! that `--bt-detach-seed-only` is present, which is what lets seeding
//! torrents stop counting against the concurrent-download budget and
//! deletes the old manual leech-precedence pause/resume hack.

const std = @import("std");

pub const Config = struct {
    /// Path/name of the aria2c binary.
    aria2c: []const u8 = "aria2c",
    /// RPC port (loopback only).
    port: u16,
    /// RPC secret token (already generated by the caller).
    secret: []const u8,
    /// Download directory.
    dir: []const u8,
    /// BitTorrent seed-ratio target. Floored at 1.0 — aria2 treats a
    /// ratio below the "already met" point as "stop immediately".
    seed_ratio: f32 = 5.0,
    /// Max seed time in minutes. 0 = no time limit (ratio governs).
    seed_time_min: u32 = 0,
    /// Concurrent active downloads.
    max_concurrent: u16 = 32,
    /// `--save-session` target. null = don't persist the aria2 session.
    session_save: ?[]const u8 = null,
    /// `--input-file` target — only set when the file already exists, else
    /// aria2 refuses to start. Usually the same path as `session_save`.
    session_load: ?[]const u8 = null,
};

/// Build the aria2c argv. Caller owns the outer slice and every string;
/// release with `free`. Allocation only — no IO.
pub fn build(alloc: std.mem.Allocator, cfg: Config) error{OutOfMemory}![]const []const u8 {
    var argv: std.ArrayList([]const u8) = .empty;
    errdefer freeList(alloc, &argv);

    // The aria2c path is borrowed (caller-owned); everything we allocPrint
    // is owned. `free` only frees owned strings, so dupe the path too to
    // keep ownership uniform.
    try argv.append(alloc, try alloc.dupe(u8, cfg.aria2c));

    // Fixed flags — duped so the whole slice has one ownership rule.
    const fixed = [_][]const u8{
        "--enable-rpc=true",
        "--rpc-listen-all=false",
        "--rpc-allow-origin-all=true",
        "--daemon=false",
        "--console-log-level=notice",
        "--check-certificate=false",
        "--continue=true",
        "--force-save=true",
        // BitTorrent: keep seeding completed torrents but detach them from
        // the concurrent-download budget so active leeches always get slots.
        "--bt-detach-seed-only=true",
        "--bt-save-metadata=true",
        "--bt-load-saved-metadata=true",
        "--enable-dht=true",
        "--enable-peer-exchange=true",
        "--bt-enable-lpd=true",
        "--listen-port=51413-51419",
        "--dht-listen-port=51420-51425",
        "--max-overall-upload-limit=0",
        "--max-overall-download-limit=0",
    };
    for (fixed) |f| try argv.append(alloc, try alloc.dupe(u8, f));

    // Templated flags.
    try argv.append(alloc, try std.fmt.allocPrint(alloc, "--rpc-listen-port={d}", .{cfg.port}));
    try argv.append(alloc, try std.fmt.allocPrint(alloc, "--rpc-secret={s}", .{cfg.secret}));
    try argv.append(alloc, try std.fmt.allocPrint(alloc, "--dir={s}", .{cfg.dir}));
    try argv.append(alloc, try std.fmt.allocPrint(alloc, "--seed-ratio={d:.2}", .{@max(cfg.seed_ratio, 1.0)}));
    try argv.append(alloc, try std.fmt.allocPrint(alloc, "--max-concurrent-downloads={d}", .{cfg.max_concurrent}));
    if (cfg.seed_time_min > 0) {
        try argv.append(alloc, try std.fmt.allocPrint(alloc, "--seed-time={d}", .{cfg.seed_time_min}));
    }
    if (cfg.session_save) |p| {
        try argv.append(alloc, try std.fmt.allocPrint(alloc, "--save-session={s}", .{p}));
        try argv.append(alloc, try alloc.dupe(u8, "--save-session-interval=30"));
    }
    if (cfg.session_load) |p| {
        try argv.append(alloc, try std.fmt.allocPrint(alloc, "--input-file={s}", .{p}));
    }

    return argv.toOwnedSlice(alloc);
}

pub fn free(alloc: std.mem.Allocator, argv: []const []const u8) void {
    for (argv) |s| alloc.free(s);
    alloc.free(argv);
}

fn freeList(alloc: std.mem.Allocator, argv: *std.ArrayList([]const u8)) void {
    for (argv.items) |s| alloc.free(s);
    argv.deinit(alloc);
}

// ---------------------------------------------------------------------------

const testing = std.testing;

fn has(argv: []const []const u8, needle: []const u8) bool {
    for (argv) |a| if (std.mem.eql(u8, a, needle)) return true;
    return false;
}

fn hasPrefix(argv: []const []const u8, prefix: []const u8) bool {
    for (argv) |a| if (std.mem.startsWith(u8, a, prefix)) return true;
    return false;
}

test "build emits the critical flags incl. bt-detach-seed-only" {
    const argv = try build(testing.allocator, .{
        .port = 6810,
        .secret = "abc123",
        .dir = "/tmp/dl",
        .seed_ratio = 5.0,
    });
    defer free(testing.allocator, argv);

    try testing.expectEqualStrings("aria2c", argv[0]);
    try testing.expect(has(argv, "--enable-rpc=true"));
    try testing.expect(has(argv, "--bt-detach-seed-only=true"));
    try testing.expect(has(argv, "--rpc-listen-port=6810"));
    try testing.expect(has(argv, "--rpc-secret=abc123"));
    try testing.expect(has(argv, "--dir=/tmp/dl"));
    try testing.expect(has(argv, "--seed-ratio=5.00"));
    try testing.expect(has(argv, "--max-concurrent-downloads=32"));
}

test "seed-ratio floored at 1.0; seed-time omitted when zero" {
    const argv = try build(testing.allocator, .{
        .port = 1,
        .secret = "s",
        .dir = "/d",
        .seed_ratio = 0.1,
        .seed_time_min = 0,
    });
    defer free(testing.allocator, argv);
    try testing.expect(has(argv, "--seed-ratio=1.00"));
    try testing.expect(!hasPrefix(argv, "--seed-time="));
}

test "session flags only when paths supplied" {
    const none = try build(testing.allocator, .{ .port = 1, .secret = "s", .dir = "/d" });
    defer free(testing.allocator, none);
    try testing.expect(!hasPrefix(none, "--save-session="));
    try testing.expect(!hasPrefix(none, "--input-file="));

    const both = try build(testing.allocator, .{
        .port = 1,
        .secret = "s",
        .dir = "/d",
        .session_save = "/d/sess",
        .session_load = "/d/sess",
        .seed_time_min = 60,
    });
    defer free(testing.allocator, both);
    try testing.expect(has(both, "--save-session=/d/sess"));
    try testing.expect(has(both, "--save-session-interval=30"));
    try testing.expect(has(both, "--input-file=/d/sess"));
    try testing.expect(has(both, "--seed-time=60"));
}
