// Auto-extracted from F95Checker's `common/structs.py` Tag enum.
// Each row: F95Checker integer tag ID → human-readable label that the
// f69 library stores. Used by the indexer mapping to translate the
// `tags: list[int]` field from `/full/{id}` into f69's `Game.tags`
// (a `[]const []const u8` of label strings).

const std = @import("std");

pub fn lookup(id: u32) ?[]const u8 {
    for (ENTRIES) |e| {
        if (e.id == id) return e.label;
    }
    return null;
}

pub const Entry = struct { id: u32, label: []const u8 };

pub const ENTRIES = [_]Entry{
    .{ .id = 1, .label = "2d game" },
    .{ .id = 2, .label = "2dcg" },
    .{ .id = 3, .label = "3d game" },
    .{ .id = 4, .label = "3dcg" },
    .{ .id = 5, .label = "adventure" },
    .{ .id = 6, .label = "ahegao" },
    .{ .id = 140, .label = "ai cg" },
    .{ .id = 7, .label = "anal sex" },
    .{ .id = 8, .label = "animated" },
    .{ .id = 9, .label = "asset-addon" },
    .{ .id = 10, .label = "asset-ai-shoujo" },
    .{ .id = 11, .label = "asset-animal" },
    .{ .id = 12, .label = "asset-animation" },
    .{ .id = 13, .label = "asset-audio" },
    .{ .id = 14, .label = "asset-bundle" },
    .{ .id = 15, .label = "asset-character" },
    .{ .id = 16, .label = "asset-clothing" },
    .{ .id = 151, .label = "asset-daz-gen1" },
    .{ .id = 141, .label = "asset-daz-gen2" },
    .{ .id = 142, .label = "asset-daz-gen3" },
    .{ .id = 143, .label = "asset-daz-gen8" },
    .{ .id = 144, .label = "asset-daz-gen81" },
    .{ .id = 145, .label = "asset-daz-gen9" },
    .{ .id = 152, .label = "asset-daz-m4" },
    .{ .id = 153, .label = "asset-daz-v4" },
    .{ .id = 17, .label = "asset-environment" },
    .{ .id = 18, .label = "asset-expression" },
    .{ .id = 146, .label = "asset-female" },
    .{ .id = 19, .label = "asset-hair" },
    .{ .id = 20, .label = "asset-hdri" },
    .{ .id = 21, .label = "asset-honey-select" },
    .{ .id = 22, .label = "asset-honey-select2" },
    .{ .id = 23, .label = "asset-koikatu" },
    .{ .id = 24, .label = "asset-light" },
    .{ .id = 147, .label = "asset-male" },
    .{ .id = 25, .label = "asset-morph" },
    .{ .id = 148, .label = "asset-nonbinary" },
    .{ .id = 150, .label = "asset-playhome" },
    .{ .id = 26, .label = "asset-plugin" },
    .{ .id = 27, .label = "asset-pose" },
    .{ .id = 28, .label = "asset-prop" },
    .{ .id = 149, .label = "asset-scene" },
    .{ .id = 29, .label = "asset-script" },
    .{ .id = 30, .label = "asset-shader" },
    .{ .id = 31, .label = "asset-texture" },
    .{ .id = 32, .label = "asset-utility" },
    .{ .id = 33, .label = "asset-vehicle" },
    .{ .id = 34, .label = "bdsm" },
    .{ .id = 35, .label = "bestiality" },
    .{ .id = 36, .label = "big ass" },
    .{ .id = 37, .label = "big tits" },
    .{ .id = 38, .label = "blackmail" },
    .{ .id = 39, .label = "bukkake" },
    .{ .id = 40, .label = "censored" },
    .{ .id = 41, .label = "character creation" },
    .{ .id = 42, .label = "cheating" },
    .{ .id = 43, .label = "combat" },
    .{ .id = 44, .label = "corruption" },
    .{ .id = 45, .label = "cosplay" },
    .{ .id = 46, .label = "creampie" },
    .{ .id = 47, .label = "dating sim" },
    .{ .id = 48, .label = "dilf" },
    .{ .id = 49, .label = "drugs" },
    .{ .id = 50, .label = "dystopian setting" },
    .{ .id = 51, .label = "exhibitionism" },
    .{ .id = 52, .label = "fantasy" },
    .{ .id = 54, .label = "female protagonist" },
    .{ .id = 53, .label = "female domination" },
    .{ .id = 55, .label = "footjob" },
    .{ .id = 56, .label = "furry" },
    .{ .id = 57, .label = "futa/trans" },
    .{ .id = 58, .label = "futa/trans protagonist" },
    .{ .id = 59, .label = "gay" },
    .{ .id = 60, .label = "graphic violence" },
    .{ .id = 61, .label = "groping" },
    .{ .id = 62, .label = "group sex" },
    .{ .id = 63, .label = "handjob" },
    .{ .id = 64, .label = "harem" },
    .{ .id = 65, .label = "horror" },
    .{ .id = 66, .label = "humiliation" },
    .{ .id = 67, .label = "humor" },
    .{ .id = 68, .label = "incest" },
    .{ .id = 69, .label = "internal view" },
    .{ .id = 70, .label = "interracial" },
    .{ .id = 71, .label = "japanese game" },
    .{ .id = 72, .label = "kinetic novel" },
    .{ .id = 73, .label = "lactation" },
    .{ .id = 74, .label = "lesbian" },
    .{ .id = 75, .label = "loli" },
    .{ .id = 77, .label = "male protagonist" },
    .{ .id = 76, .label = "male domination" },
    .{ .id = 78, .label = "management" },
    .{ .id = 79, .label = "masturbation" },
    .{ .id = 80, .label = "milf" },
    .{ .id = 81, .label = "mind control" },
    .{ .id = 82, .label = "mobile game" },
    .{ .id = 83, .label = "monster" },
    .{ .id = 84, .label = "monster girl" },
    .{ .id = 85, .label = "multiple endings" },
    .{ .id = 86, .label = "multiple penetration" },
    .{ .id = 87, .label = "multiple protagonist" },
    .{ .id = 88, .label = "necrophilia" },
    .{ .id = 89, .label = "no sexual content" },
    .{ .id = 90, .label = "netorare" },
    .{ .id = 91, .label = "oral sex" },
    .{ .id = 92, .label = "paranormal" },
    .{ .id = 93, .label = "parody" },
    .{ .id = 94, .label = "platformer" },
    .{ .id = 95, .label = "point & click" },
    .{ .id = 96, .label = "possession" },
    .{ .id = 97, .label = "pov" },
    .{ .id = 98, .label = "pregnancy" },
    .{ .id = 99, .label = "prostitution" },
    .{ .id = 100, .label = "puzzle" },
    .{ .id = 101, .label = "rape" },
    .{ .id = 102, .label = "real porn" },
    .{ .id = 103, .label = "religion" },
    .{ .id = 104, .label = "romance" },
    .{ .id = 105, .label = "rpg" },
    .{ .id = 106, .label = "sandbox" },
    .{ .id = 107, .label = "scat" },
    .{ .id = 108, .label = "school setting" },
    .{ .id = 109, .label = "sci-fi" },
    .{ .id = 110, .label = "sex toys" },
    .{ .id = 111, .label = "sexual harassment" },
    .{ .id = 112, .label = "shooter" },
    .{ .id = 113, .label = "shota" },
    .{ .id = 114, .label = "side-scroller" },
    .{ .id = 115, .label = "simulator" },
    .{ .id = 116, .label = "sissification" },
    .{ .id = 117, .label = "slave" },
    .{ .id = 118, .label = "sleep sex" },
    .{ .id = 119, .label = "spanking" },
    .{ .id = 120, .label = "strategy" },
    .{ .id = 121, .label = "stripping" },
    .{ .id = 122, .label = "superpowers" },
    .{ .id = 123, .label = "swinging" },
    .{ .id = 124, .label = "teasing" },
    .{ .id = 125, .label = "tentacles" },
    .{ .id = 126, .label = "text based" },
    .{ .id = 127, .label = "titfuck" },
    .{ .id = 128, .label = "trainer" },
    .{ .id = 129, .label = "transformation" },
    .{ .id = 130, .label = "trap" },
    .{ .id = 131, .label = "turn based combat" },
    .{ .id = 132, .label = "twins" },
    .{ .id = 133, .label = "urination" },
    .{ .id = 134, .label = "vaginal sex" },
    .{ .id = 135, .label = "virgin" },
    .{ .id = 136, .label = "virtual reality" },
    .{ .id = 137, .label = "voiced" },
    .{ .id = 138, .label = "vore" },
    .{ .id = 139, .label = "voyeurism" },
};

test "lookup known ids" {
    try std.testing.expectEqualStrings("2d game", lookup(1).?);
    try std.testing.expectEqualStrings("ai cg", lookup(140).?);
    try std.testing.expectEqualStrings("netorare", lookup(90).?);
    try std.testing.expectEqualStrings("point & click", lookup(95).?);
    try std.testing.expectEqualStrings("futa/trans", lookup(57).?);
    try std.testing.expectEqualStrings("asset-daz-v4", lookup(153).?);
    try std.testing.expectEqual(@as(?[]const u8, null), lookup(0));
    try std.testing.expectEqual(@as(?[]const u8, null), lookup(9999));
}
